spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: user
      password: changeme
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        show-sql: true
        hbm2ddl-auto: update
